App6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'App6'

urlpatterns = [
    path('', views.Index , name='Index'),
    path('challenge', include("challenge.urls"))
]

Project6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("App6.urls")),
    path('challenge/', include("challenge.urls"))
]

challenge/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views 

app_name = 'challenge'

urlpatterns = [
    path('', views.challenge, name='challenge'),
]

App6/models.py
from django.db import models

# Create your models here.

class Mind(models.Model):
    mind = models.CharField(primary_key=True, max_length=100)
    time = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.mind}"
    

challenge/models.py
from django.db import models

# Create your models here.

App6/forms.py
from django import forms
from .models import Mind

class Mindform(forms.ModelForm):
    class Meta:
        model = Mind
        fields = '__all__'
    mind = forms.CharField(
        label = "",
        max_length = 30
    )

App6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Mind
from .forms import Mindform

def Index(request):
    if request.method=="POST":
        frm = Mindform(request.POST)
        if frm.is_valid():
            mdl = Mind(mind=frm.cleaned_data["mind"])
            # mdl.mind = frm.cleaned_data["mind"]
            mdl.save()
        return redirect("/")
    frm = Mindform()
    mdl = Mind.objects.all()
    frm_dictio = {
        'Mindform':frm,
        'Mind':mdl
    }
    return render(request,'Index.html',frm_dictio)
    # {'mdl':Mindform,'data':data})

# Create your views here.

challenge/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

def challenge(request):
    return render(request,'challenge.html')

App6/templates/Index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Status</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="static/style2.css">
</head>

<body>
    <div class="form">
        <form action="{% url 'App6:Index' %}" id="form" , method="POST">
            <h1>What's on your mind?</h1>
            {% csrf_token %} {{ Mindform.as_p }}
            <button type="submit" class="buttons">Submit</button>
        </form>
    </div>
    <div class="table">
        <table class="table1">
            {% for i in Mind %}
            <tr>
                <td>{{i.mind}}<br>{{i.time}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</body>

challenge/templates/challenge.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>challenge</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="static/style2.css">
</head>

<body>
    <b>1906316603</b>
</body>